In [1]:
import numpy as np

In [16]:
np.random.seed(42)                   #seed for generating random numbers
data = np.random.random((3,4))       #generate random numbers of shape (3,4)
data

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [17]:
data.dtype                          #data type of our data

dtype('float64')

In [19]:
np.arange(12,20,1.9)               #arange numbers from 12 to 20 with a gap of 1.9 between each numbers

array([12. , 13.9, 15.8, 17.7, 19.6])

In [20]:
np.arange(0,10)                    #arange numbers from 0 to 10 with a gap of 1 between each numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(3,4,5)                 #generate numbers from 3 to 4 with 5 numbers

array([3.  , 3.25, 3.5 , 3.75, 4.  ])

In [23]:
np.zeros((3,5))                    #generate (3,5) matrix of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((2,9))                    #generate (2,9) matrix of ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
a = np.random.random((2,4))
b = np.ones((2,4))

In [26]:
a*b                              #element-wise multiplication

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [27]:
a+b                              #element-wise addition

array([[1.83244264, 1.21233911, 1.18182497, 1.18340451],
       [1.30424224, 1.52475643, 1.43194502, 1.29122914]])

In [28]:
a-b                             #element-wise subtraction

array([[-0.16755736, -0.78766089, -0.81817503, -0.81659549],
       [-0.69575776, -0.47524357, -0.56805498, -0.70877086]])

In [29]:
a/b                         #element-wise division

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [31]:
c = np.random.random((5,9))
d = np.ones((9,5))

In [32]:
c.dot(d)    #dot product,i.e,multiplication of first row of c with first column of d and so on(Regular matrix multiplication)

array([[3.95742198, 3.95742198, 3.95742198, 3.95742198, 3.95742198],
       [4.01477178, 4.01477178, 4.01477178, 4.01477178, 4.01477178],
       [3.91832293, 3.91832293, 3.91832293, 3.91832293, 3.91832293],
       [6.35045071, 6.35045071, 6.35045071, 6.35045071, 6.35045071],
       [2.78148465, 2.78148465, 2.78148465, 2.78148465, 2.78148465]])

In [33]:
d.dot(c)   #dot product,i.e,multiplication of first row of d with first column of c and so on(Regular matrix multiplication)

array([[1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],


In [34]:
np.dot(c,d) #dot product,i.e,multiplication of first row of c with first column of d and so on(Regular matrix multiplication)

array([[3.95742198, 3.95742198, 3.95742198, 3.95742198, 3.95742198],
       [4.01477178, 4.01477178, 4.01477178, 4.01477178, 4.01477178],
       [3.91832293, 3.91832293, 3.91832293, 3.91832293, 3.91832293],
       [6.35045071, 6.35045071, 6.35045071, 6.35045071, 6.35045071],
       [2.78148465, 2.78148465, 2.78148465, 2.78148465, 2.78148465]])

In [35]:
np.dot(d,c) #dot product,i.e,multiplication of first row of d with first column of c and so on(Regular matrix multiplication)

array([[1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],
       [1.95109686, 1.92988435, 0.81478875, 2.2215053 , 2.60315416,
        3.87097637, 2.99041597, 2.4360238 , 2.2046065 ],


In [37]:
c[0,1] #indexing - 0th row & 1st column of c or 1st column of 0th row

0.13949386065204183

In [38]:
c[0]  #indexing - 0th row and all columns or all columns of 0th row

array([0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457])

In [39]:
np.apply_along_axis(np.std,arr=d,axis=0) #apply std deviation along all elements along 0th axis of array d

array([0., 0., 0., 0., 0.])

In [40]:
np.apply_along_axis(np.sum,arr=d,axis=1) #summation of all elements along 1st axis of array d

array([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [41]:
np.apply_along_axis(np.mean,arr=c,axis=0)#apply mean along all elements along 0th axis of array c

array([0.39021937, 0.38597687, 0.16295775, 0.44430106, 0.52063083,
       0.77419527, 0.59808319, 0.48720476, 0.4409213 ])

In [42]:
np.apply_along_axis(np.mean,arr=c,axis=1)#apply mean along all elements along 1st axis of array c

array([0.43971355, 0.44608575, 0.43536921, 0.70560563, 0.30905385])

In [60]:
e = np.random.random((2,5))
f = np.random.random((2,5))

In [51]:
np.column_stack((e,f))                  #stack all elements of e and f along the column

array([[0.892559  , 0.53934224, 0.80744016, 0.8960913 , 0.31800347,
        0.00695213, 0.5107473 , 0.417411  , 0.22210781, 0.11986537],
       [0.11005192, 0.22793516, 0.42710779, 0.81801477, 0.86073058,
        0.33761517, 0.9429097 , 0.32320293, 0.51879062, 0.70301896]])

In [52]:
np.row_stack((e,f))                    #stack all elements of e and f along the row

array([[0.892559  , 0.53934224, 0.80744016, 0.8960913 , 0.31800347],
       [0.11005192, 0.22793516, 0.42710779, 0.81801477, 0.86073058],
       [0.00695213, 0.5107473 , 0.417411  , 0.22210781, 0.11986537],
       [0.33761517, 0.9429097 , 0.32320293, 0.51879062, 0.70301896]])

In [55]:
np.vsplit(e,1)                        #split the elements vertically with 1 row in for each split

[array([[0.892559  , 0.53934224, 0.80744016, 0.8960913 , 0.31800347],
        [0.11005192, 0.22793516, 0.42710779, 0.81801477, 0.86073058]])]

In [61]:
np.hsplit(f,1)                        #split the elements horizontally with 1 column for each split

[array([[0.67756436, 0.01658783, 0.51209306, 0.22649578, 0.64517279],
        [0.17436643, 0.69093774, 0.38673535, 0.93672999, 0.13752094]])]

In [62]:
np.vstack((f,e))                      #stack the elements vertically with 1 row in for each stack

array([[0.67756436, 0.01658783, 0.51209306, 0.22649578, 0.64517279],
       [0.17436643, 0.69093774, 0.38673535, 0.93672999, 0.13752094],
       [0.36778313, 0.63230583, 0.63352971, 0.53577468, 0.09028977],
       [0.8353025 , 0.32078006, 0.18651851, 0.04077514, 0.59089294]])

In [63]:
np.hstack((f,e))                    #stack the elements horizontally with 1 column for each stack

array([[0.67756436, 0.01658783, 0.51209306, 0.22649578, 0.64517279,
        0.36778313, 0.63230583, 0.63352971, 0.53577468, 0.09028977],
       [0.17436643, 0.69093774, 0.38673535, 0.93672999, 0.13752094,
        0.8353025 , 0.32078006, 0.18651851, 0.04077514, 0.59089294]])

# Pandas

In [64]:
import pandas as pd

In [66]:
series = pd.Series([1,5,8,5])
series

0    1
1    5
2    8
3    5
dtype: int64

In [68]:
series1 = pd.Series([3,4,5,1,5],index=['a','b','c','d','e'])
series1

a    3
b    4
c    5
d    1
e    5
dtype: int64

In [70]:
series1['a']

3

In [71]:
series[1]

5

In [73]:
series1[['a','d']]

a    3
d    1
dtype: int64

In [75]:
series[[1,3]]

1    5
3    5
dtype: int64

In [78]:
dictionary = {'India':1234,'USA':132,'Spain':432}
series2 = pd.Series(dictionary)

series2

India    1234
USA       132
Spain     432
dtype: int64

In [79]:
series2[['India','USA']]

India    1234
USA       132
dtype: int64

In [84]:
dataframe = pd.DataFrame(series2)
dataframe

0
India  1234
USA     132
Spain   432

In [88]:
dataframe.loc[['India','Spain']]

0
India  1234
Spain   432

In [89]:
dataframe.loc['India'][0]

1234

In [90]:
dataframe.loc['India']

0    1234
Name: India, dtype: int64